Controllers/AddressesController.cs
using ITSAIntermediate_VelaphiMhlanga.Data;
using ITSAIntermediate_VelaphiMhlanga.Models;
using ITSAIntermediate_VelaphiMhlanga.Models.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ITSAIntermediate_VelaphiMhlanga.Controllers
{
    [Authorize]
    public class AddressesController : Controller
    {
        private readonly ApplicationDbContext applicationDbContext;

        public AddressesController(ApplicationDbContext applicationDbContext)
        {
            this.applicationDbContext = applicationDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var addresses = await applicationDbContext.Addresses.ToListAsync();
            return View(addresses);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddAddressViewModel addAddressRequest)
        {
            var address = new Address()
            {
                Id = Guid.NewGuid(),
                Country = addAddressRequest.Country,
                Province = addAddressRequest.Province,
                City = addAddressRequest.City,
                Suburb = addAddressRequest.Suburb,
                PostalCode = addAddressRequest.PostalCode,
                UnitNumber = addAddressRequest.UnitNumber,
                ComplexName = addAddressRequest.ComplexName,
            };

            await applicationDbContext.Addresses.AddAsync(address);
            await applicationDbContext.SaveChangesAsync();
            return RedirectToAction("Index");

        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            var addresses = await applicationDbContext.Addresses.FirstOrDefaultAsync(x => x.Id == id);

            if (addresses != null)
            {
                var viewModel = new UpdateAddressViewModel()
                {
                    Id = addresses.Id,
                    Country = addresses.Country,
                    Province = addresses.Province,
                    City = addresses.City,
                    Suburb = addresses.Suburb,
                    PostalCode = addresses.PostalCode,
                    UnitNumber = addresses.UnitNumber,
                    ComplexName = addresses.ComplexName,
                };

                return await Task.Run(() => View("View", viewModel));

            }


            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateAddressViewModel model)
        {
            var addresses = await applicationDbContext.Addresses.FindAsync(model.Id);

            if (addresses != null)
            {
                addresses.Country = model.Country;
                addresses.Province = model.Province;
                addresses.City = model.City;
                addresses.Suburb = model.Suburb;
                addresses.PostalCode = model.PostalCode;
                addresses.UnitNumber = model.UnitNumber;
                addresses.ComplexName = model.ComplexName;

                await applicationDbContext.SaveChangesAsync();

                return RedirectToAction("Index");

            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateAddressViewModel model)
        {
            var addresses = await applicationDbContext.Addresses.FindAsync(model.Id);

            if (addresses != null)
            {
                applicationDbContext.Addresses.Remove(addresses);
                await applicationDbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/EmployeeDetailsController.cs
using ITSAIntermediate_VelaphiMhlanga.Data;
using ITSAIntermediate_VelaphiMhlanga.Models;
using ITSAIntermediate_VelaphiMhlanga.Models.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ITSAIntermediate_VelaphiMhlanga.Controllers
{
    [Authorize]
    public class EmployeeDetailsController : Controller
    {
        private readonly ApplicationDbContext applicationDbContext;

        public EmployeeDetailsController(ApplicationDbContext applicationDbContext)
        {
            this.applicationDbContext = applicationDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var employeeDetails = await applicationDbContext.EmployeeDetails.ToListAsync();
            return View(employeeDetails);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddEmployeeDetailsViewModel addEmployeeDetailsRequest)
        {
            var employeeDetail = new EmployeeDetail()
            {
                Id = Guid.NewGuid(),
                Department = addEmployeeDetailsRequest.Department,
                eRole = addEmployeeDetailsRequest.eRole,
                Salary = addEmployeeDetailsRequest.Salary,



            };

            await applicationDbContext.EmployeeDetails.AddAsync(employeeDetail);
            await applicationDbContext.SaveChangesAsync();
            return RedirectToAction("Index");

        }

        [HttpGet]
        public async Task<IActionResult>? View(Guid id)
        {
            var employeeDetails = await applicationDbContext.EmployeeDetails.FirstOrDefaultAsync(x => x.Id == id);

            if (employeeDetails != null)
            {
                var viewModel = new UpdateEmployeeDetailsViewModel()
                {

                    Id = employeeDetails.Id,
                    Department = employeeDetails.Department,
                    eRole = employeeDetails.eRole,
                    Salary = employeeDetails.Salary,

                };

                return await Task.Run(() => View("View", viewModel));
            }


            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateEmployeeDetailsViewModel model)
        {
            var employeeDetails = await applicationDbContext.EmployeeDetails.FindAsync(model.Id);

            if (employeeDetails != null)
            {
                employeeDetails.Department = model.Department;
                employeeDetails.eRole = model.eRole;
                employeeDetails.Salary = model.Salary;

                await applicationDbContext.SaveChangesAsync();

                return RedirectToAction("Index");

            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateRecUserViewModel model)
        {
            var employeeDetails = await applicationDbContext.EmployeeDetails.FindAsync(model.Id);

            if (employeeDetails != null)
            {
                applicationDbContext.EmployeeDetails.Remove(employeeDetails);
                await applicationDbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

    }
}

Controllers/RecUsersController.cs
using ITSAIntermediate_VelaphiMhlanga.Data;
using ITSAIntermediate_VelaphiMhlanga.Models;
using ITSAIntermediate_VelaphiMhlanga.Models.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace ITSAIntermediate_VelaphiMhlanga.Controllers
{
    [Authorize]

    public class RecUsersController : Controller
    {
        private readonly ApplicationDbContext applicationDbContext;

        public RecUsersController(ApplicationDbContext applicationDbContext)
        {
            this.applicationDbContext = applicationDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var recUsers = await applicationDbContext.RecUsers.ToListAsync();
            return View(recUsers);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddRecUsersViewModel addRecUserRequest)
        {
            var recUser = new RecUser()
            {
                Id = Guid.NewGuid(),
                Name = addRecUserRequest.Name,
                Surname = addRecUserRequest.Surname,
                DateOfBirth = addRecUserRequest.DateOfBirth,
                IdentityNumber = addRecUserRequest.IdentityNumber,
                Address = addRecUserRequest.Address,
                EmailAddress = addRecUserRequest.EmailAddress,
                ContactNumber = addRecUserRequest.ContactNumber

            };

            await applicationDbContext.RecUsers.AddAsync(recUser);
            await applicationDbContext.SaveChangesAsync();
            return RedirectToAction("Index");

        }

        [HttpGet]
        public async Task<IActionResult> View(Guid id)
        {
            var recUsers = await applicationDbContext.RecUsers.FirstOrDefaultAsync(x => x.Id == id);

            if (recUsers != null)
            {
                var viewModel = new UpdateRecUserViewModel()
                {

                    Id = recUsers.Id,
                    Name = recUsers.Name,
                    Surname = recUsers.Surname,
                    DateOfBirth = recUsers.DateOfBirth,
                    IdentityNumber = recUsers.IdentityNumber,
                    Address = recUsers.Address,
                    EmailAddress = recUsers.EmailAddress,
                    ContactNumber = recUsers.ContactNumber
                };

                return await Task.Run(() => View("View", viewModel));
            }


            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> View(UpdateRecUserViewModel model)
        {
            var recUsers = await applicationDbContext.RecUsers.FindAsync(model.Id);

            if (recUsers != null)
            {
                recUsers.Name = model.Name;
                recUsers.Surname = model.Surname;
                recUsers.DateOfBirth = model.DateOfBirth;
                recUsers.IdentityNumber = model.IdentityNumber;
                recUsers.Address = model.Address;
                recUsers.EmailAddress = model.EmailAddress;
                recUsers.ContactNumber = model.ContactNumber;

                await applicationDbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");

        }

        [HttpPost]
        public async Task<IActionResult> Delete(UpdateRecUserViewModel model)
        {
            var recUsers = await applicationDbContext.RecUsers.FindAsync(model.Id);

            if (recUsers != null)
            {

                applicationDbContext.RecUsers.Remove(recUsers);
                await applicationDbContext.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ITSAIntermediate_VelaphiMhlang</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />  
    <link rel="stylesheet" href="~/ITSAIntermediate_VelaphiMhlanga.styles.css" asp-append-version="true" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RecUsers" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RecUsers" asp-action="Add">NewUser</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmployeeDetails" asp-action="index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmployeeDetails" asp-action="Add">NewEmployee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Addresses" asp-action="Index">Addresses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Addresses" asp-action="Add">NewAddress</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CompanyDetails" asp-action="Index">Companies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CompanyDetails" asp-action="Add">newCompany</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
            <partial name="_LoginPartial"/>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ITSAIntermediate_VelaphiMhlanga - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
   
    <script src="~/js/site.js" asp-append-version="true"></script>   
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>